language: python
os: linux
dist: xenial
python:
    - "3.7"
jobs:
    include:
        before_install:
        - python -m pip install --upgrade pip
install:
    - pip freeze > requirements.txt
    - pip install -r requirements.txt
script:
    - pwd
    - ls /home
    - python -m unittest discover
    - /home/travis/build/Hydman/softWareTest202006/sonar-scanner-cli-4.3.0.2102-linux/bin/sonar-scanner.bat