language: python
os: linux
dist: xenial
python:
    - "3.7"
jobs:
    include:
        before_install:
        - python -m pip install --upgrade pip
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-linux.zip
        - unzip sonar-scanner-cli-4.3.0.2102-linux.zip -d /tmp
        - export PATH = $PATH:/tmp/sonar-scanner-cli-4.3.0.2102-linux/bin
install:
    - pip freeze > requirements.txt
    - pip install -r requirements.txt
script:
    - python -m unittest discover
    - sonar-scanner \
        -Dsonar.projectKey=D0642121_finalPresentation \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://140.134.24.239:9000 \
        -Dsonar.login=70bf2fe58011c83b2dbb0c4d89a672d2f0527e59