language: python
os:linux
dist:xenial
python:
    - "3.7"
jobs:
    include:
        before_install:
        - python -m pip install --upgrade pip
install:
    - pip freeze > requirements.txt
    - pip install -r requirements.txt
script:
    - dir
    - python -m unittest discover