language: python
# os: linux(windows, osx)
os: linux
dist: xenial
python:
	- "3.7"
# virtualenv:
#	system_site_packages: true
install:
#	- pip install --user -r requirement.txt
	- pip install -r requirements.txt
# 	- pip install .
# script: pytest
# script: make test
script:
	- python -m unittest discover